version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: smart_attendance_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smart_attendance_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:${POSTGRES_PASSWORD}@db:5432/attendance_db
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  pgdata:
